name: Test & Publish 📦 to PyPI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        allow-failure: [false]
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
        include:
          - python-version: "3.12"
            allow-failure: true
          - python-version: "3.13"
            allow-failure: true

    continue-on-error: ${{ matrix.allow-failure }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test

  publish:
    needs: test
    runs-on: ubuntu-latest
    env:
      python_version: 3.13

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f build-requirements.txt ]; then pip install -r build-requirements.txt; fi

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
